"""empty message

Revision ID: 290c4039b962
Revises: 92fab1095a4d
Create Date: 2023-04-15 11:26:55.130265

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '290c4039b962'
down_revision = '92fab1095a4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wsrequestlog_authorization', table_name='wsrequestlog')
    op.drop_index('ix_wsrequestlog_created', table_name='wsrequestlog')
    op.drop_index('ix_wsrequestlog_id', table_name='wsrequestlog')
    op.drop_index('ix_wsrequestlog_method', table_name='wsrequestlog')
    op.drop_index('ix_wsrequestlog_modified', table_name='wsrequestlog')
    op.drop_index('ix_wsrequestlog_request', table_name='wsrequestlog')
    op.drop_index('ix_wsrequestlog_service_name', table_name='wsrequestlog')
    op.drop_index('ix_wsrequestlog_status_code', table_name='wsrequestlog')
    op.drop_table('wsrequestlog')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wsrequestlog',
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('modified', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('authorization', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('method', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('status_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('service_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('request', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='wsrequestlog_pkey')
    )
    op.create_index('ix_wsrequestlog_status_code', 'wsrequestlog', ['status_code'], unique=False)
    op.create_index('ix_wsrequestlog_service_name', 'wsrequestlog', ['service_name'], unique=False)
    op.create_index('ix_wsrequestlog_request', 'wsrequestlog', ['request'], unique=False)
    op.create_index('ix_wsrequestlog_modified', 'wsrequestlog', ['modified'], unique=False)
    op.create_index('ix_wsrequestlog_method', 'wsrequestlog', ['method'], unique=False)
    op.create_index('ix_wsrequestlog_id', 'wsrequestlog', ['id'], unique=False)
    op.create_index('ix_wsrequestlog_created', 'wsrequestlog', ['created'], unique=False)
    op.create_index('ix_wsrequestlog_authorization', 'wsrequestlog', ['authorization'], unique=False)
    # ### end Alembic commands ###
