"""empty message

Revision ID: 6b05f5028e16
Revises: 290c4039b962
Create Date: 2023-10-02 17:10:59.380475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b05f5028e16'
down_revision = '290c4039b962'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_requestlog_authorization', table_name='requestlog')
    op.drop_index('ix_requestlog_ip', table_name='requestlog')
    op.drop_index('ix_requestlog_method', table_name='requestlog')
    op.drop_index('ix_requestlog_request', table_name='requestlog')
    op.drop_index('ix_requestlog_service_name', table_name='requestlog')
    op.drop_index('ix_requestlog_trace', table_name='requestlog')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_requestlog_trace', 'requestlog', ['trace'], unique=False)
    op.create_index('ix_requestlog_service_name', 'requestlog', ['service_name'], unique=False)
    op.create_index('ix_requestlog_request', 'requestlog', ['request'], unique=False)
    op.create_index('ix_requestlog_method', 'requestlog', ['method'], unique=False)
    op.create_index('ix_requestlog_ip', 'requestlog', ['ip'], unique=False)
    op.create_index('ix_requestlog_authorization', 'requestlog', ['authorization'], unique=False)
    # ### end Alembic commands ###
